// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: system_monitor.proto

#ifndef PROTOBUF_INCLUDED_system_5fmonitor_2eproto
#define PROTOBUF_INCLUDED_system_5fmonitor_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_system_5fmonitor_2eproto 

namespace protobuf_system_5fmonitor_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[2];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_system_5fmonitor_2eproto
namespace systemmonitor {
class CpuUsageRequest;
class CpuUsageRequestDefaultTypeInternal;
extern CpuUsageRequestDefaultTypeInternal _CpuUsageRequest_default_instance_;
class CpuUsageResponse;
class CpuUsageResponseDefaultTypeInternal;
extern CpuUsageResponseDefaultTypeInternal _CpuUsageResponse_default_instance_;
}  // namespace systemmonitor
namespace google {
namespace protobuf {
template<> ::systemmonitor::CpuUsageRequest* Arena::CreateMaybeMessage<::systemmonitor::CpuUsageRequest>(Arena*);
template<> ::systemmonitor::CpuUsageResponse* Arena::CreateMaybeMessage<::systemmonitor::CpuUsageResponse>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace systemmonitor {

// ===================================================================

class CpuUsageRequest : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:systemmonitor.CpuUsageRequest) */ {
 public:
  CpuUsageRequest();
  virtual ~CpuUsageRequest();

  CpuUsageRequest(const CpuUsageRequest& from);

  inline CpuUsageRequest& operator=(const CpuUsageRequest& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  CpuUsageRequest(CpuUsageRequest&& from) noexcept
    : CpuUsageRequest() {
    *this = ::std::move(from);
  }

  inline CpuUsageRequest& operator=(CpuUsageRequest&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const CpuUsageRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const CpuUsageRequest* internal_default_instance() {
    return reinterpret_cast<const CpuUsageRequest*>(
               &_CpuUsageRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(CpuUsageRequest* other);
  friend void swap(CpuUsageRequest& a, CpuUsageRequest& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline CpuUsageRequest* New() const final {
    return CreateMaybeMessage<CpuUsageRequest>(NULL);
  }

  CpuUsageRequest* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<CpuUsageRequest>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const CpuUsageRequest& from);
  void MergeFrom(const CpuUsageRequest& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CpuUsageRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:systemmonitor.CpuUsageRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_system_5fmonitor_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class CpuUsageResponse : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:systemmonitor.CpuUsageResponse) */ {
 public:
  CpuUsageResponse();
  virtual ~CpuUsageResponse();

  CpuUsageResponse(const CpuUsageResponse& from);

  inline CpuUsageResponse& operator=(const CpuUsageResponse& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  CpuUsageResponse(CpuUsageResponse&& from) noexcept
    : CpuUsageResponse() {
    *this = ::std::move(from);
  }

  inline CpuUsageResponse& operator=(CpuUsageResponse&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const CpuUsageResponse& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const CpuUsageResponse* internal_default_instance() {
    return reinterpret_cast<const CpuUsageResponse*>(
               &_CpuUsageResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(CpuUsageResponse* other);
  friend void swap(CpuUsageResponse& a, CpuUsageResponse& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline CpuUsageResponse* New() const final {
    return CreateMaybeMessage<CpuUsageResponse>(NULL);
  }

  CpuUsageResponse* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<CpuUsageResponse>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const CpuUsageResponse& from);
  void MergeFrom(const CpuUsageResponse& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CpuUsageResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // float usage_percent = 1;
  void clear_usage_percent();
  static const int kUsagePercentFieldNumber = 1;
  float usage_percent() const;
  void set_usage_percent(float value);

  // @@protoc_insertion_point(class_scope:systemmonitor.CpuUsageResponse)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  float usage_percent_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_system_5fmonitor_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// CpuUsageRequest

// -------------------------------------------------------------------

// CpuUsageResponse

// float usage_percent = 1;
inline void CpuUsageResponse::clear_usage_percent() {
  usage_percent_ = 0;
}
inline float CpuUsageResponse::usage_percent() const {
  // @@protoc_insertion_point(field_get:systemmonitor.CpuUsageResponse.usage_percent)
  return usage_percent_;
}
inline void CpuUsageResponse::set_usage_percent(float value) {
  
  usage_percent_ = value;
  // @@protoc_insertion_point(field_set:systemmonitor.CpuUsageResponse.usage_percent)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace systemmonitor

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_system_5fmonitor_2eproto
