// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: system_monitor.proto
#ifndef GRPC_system_5fmonitor_2eproto__INCLUDED
#define GRPC_system_5fmonitor_2eproto__INCLUDED

#include "system_monitor.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace systemmonitor {

class SystemMonitor final {
 public:
  static constexpr char const* service_full_name() {
    return "systemmonitor.SystemMonitor";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status GetCpuUsage(::grpc::ClientContext* context, const ::systemmonitor::CpuUsageRequest& request, ::systemmonitor::CpuUsageResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::systemmonitor::CpuUsageResponse>> AsyncGetCpuUsage(::grpc::ClientContext* context, const ::systemmonitor::CpuUsageRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::systemmonitor::CpuUsageResponse>>(AsyncGetCpuUsageRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::systemmonitor::CpuUsageResponse>> PrepareAsyncGetCpuUsage(::grpc::ClientContext* context, const ::systemmonitor::CpuUsageRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::systemmonitor::CpuUsageResponse>>(PrepareAsyncGetCpuUsageRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void GetCpuUsage(::grpc::ClientContext* context, const ::systemmonitor::CpuUsageRequest* request, ::systemmonitor::CpuUsageResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetCpuUsage(::grpc::ClientContext* context, const ::systemmonitor::CpuUsageRequest* request, ::systemmonitor::CpuUsageResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::systemmonitor::CpuUsageResponse>* AsyncGetCpuUsageRaw(::grpc::ClientContext* context, const ::systemmonitor::CpuUsageRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::systemmonitor::CpuUsageResponse>* PrepareAsyncGetCpuUsageRaw(::grpc::ClientContext* context, const ::systemmonitor::CpuUsageRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status GetCpuUsage(::grpc::ClientContext* context, const ::systemmonitor::CpuUsageRequest& request, ::systemmonitor::CpuUsageResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::systemmonitor::CpuUsageResponse>> AsyncGetCpuUsage(::grpc::ClientContext* context, const ::systemmonitor::CpuUsageRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::systemmonitor::CpuUsageResponse>>(AsyncGetCpuUsageRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::systemmonitor::CpuUsageResponse>> PrepareAsyncGetCpuUsage(::grpc::ClientContext* context, const ::systemmonitor::CpuUsageRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::systemmonitor::CpuUsageResponse>>(PrepareAsyncGetCpuUsageRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void GetCpuUsage(::grpc::ClientContext* context, const ::systemmonitor::CpuUsageRequest* request, ::systemmonitor::CpuUsageResponse* response, std::function<void(::grpc::Status)>) override;
      void GetCpuUsage(::grpc::ClientContext* context, const ::systemmonitor::CpuUsageRequest* request, ::systemmonitor::CpuUsageResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::systemmonitor::CpuUsageResponse>* AsyncGetCpuUsageRaw(::grpc::ClientContext* context, const ::systemmonitor::CpuUsageRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::systemmonitor::CpuUsageResponse>* PrepareAsyncGetCpuUsageRaw(::grpc::ClientContext* context, const ::systemmonitor::CpuUsageRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_GetCpuUsage_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status GetCpuUsage(::grpc::ServerContext* context, const ::systemmonitor::CpuUsageRequest* request, ::systemmonitor::CpuUsageResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_GetCpuUsage : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetCpuUsage() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_GetCpuUsage() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetCpuUsage(::grpc::ServerContext* /*context*/, const ::systemmonitor::CpuUsageRequest* /*request*/, ::systemmonitor::CpuUsageResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetCpuUsage(::grpc::ServerContext* context, ::systemmonitor::CpuUsageRequest* request, ::grpc::ServerAsyncResponseWriter< ::systemmonitor::CpuUsageResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_GetCpuUsage<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_GetCpuUsage : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetCpuUsage() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::systemmonitor::CpuUsageRequest, ::systemmonitor::CpuUsageResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::systemmonitor::CpuUsageRequest* request, ::systemmonitor::CpuUsageResponse* response) { return this->GetCpuUsage(context, request, response); }));}
    void SetMessageAllocatorFor_GetCpuUsage(
        ::grpc::MessageAllocator< ::systemmonitor::CpuUsageRequest, ::systemmonitor::CpuUsageResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::systemmonitor::CpuUsageRequest, ::systemmonitor::CpuUsageResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetCpuUsage() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetCpuUsage(::grpc::ServerContext* /*context*/, const ::systemmonitor::CpuUsageRequest* /*request*/, ::systemmonitor::CpuUsageResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetCpuUsage(
      ::grpc::CallbackServerContext* /*context*/, const ::systemmonitor::CpuUsageRequest* /*request*/, ::systemmonitor::CpuUsageResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_GetCpuUsage<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_GetCpuUsage : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetCpuUsage() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_GetCpuUsage() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetCpuUsage(::grpc::ServerContext* /*context*/, const ::systemmonitor::CpuUsageRequest* /*request*/, ::systemmonitor::CpuUsageResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetCpuUsage : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetCpuUsage() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_GetCpuUsage() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetCpuUsage(::grpc::ServerContext* /*context*/, const ::systemmonitor::CpuUsageRequest* /*request*/, ::systemmonitor::CpuUsageResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetCpuUsage(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetCpuUsage : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetCpuUsage() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetCpuUsage(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetCpuUsage() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetCpuUsage(::grpc::ServerContext* /*context*/, const ::systemmonitor::CpuUsageRequest* /*request*/, ::systemmonitor::CpuUsageResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetCpuUsage(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetCpuUsage : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetCpuUsage() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::systemmonitor::CpuUsageRequest, ::systemmonitor::CpuUsageResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::systemmonitor::CpuUsageRequest, ::systemmonitor::CpuUsageResponse>* streamer) {
                       return this->StreamedGetCpuUsage(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetCpuUsage() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetCpuUsage(::grpc::ServerContext* /*context*/, const ::systemmonitor::CpuUsageRequest* /*request*/, ::systemmonitor::CpuUsageResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetCpuUsage(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::systemmonitor::CpuUsageRequest,::systemmonitor::CpuUsageResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_GetCpuUsage<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_GetCpuUsage<Service > StreamedService;
};

}  // namespace systemmonitor


#endif  // GRPC_system_5fmonitor_2eproto__INCLUDED
