// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: System_Monitor.proto

#include "System_Monitor.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace systemmonitor {
class CpuUsageRequestDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<CpuUsageRequest>
      _instance;
} _CpuUsageRequest_default_instance_;
class CpuUsageResponseDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<CpuUsageResponse>
      _instance;
} _CpuUsageResponse_default_instance_;
}  // namespace systemmonitor
namespace protobuf_System_5fMonitor_2eproto {
static void InitDefaultsCpuUsageRequest() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::systemmonitor::_CpuUsageRequest_default_instance_;
    new (ptr) ::systemmonitor::CpuUsageRequest();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::systemmonitor::CpuUsageRequest::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_CpuUsageRequest =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsCpuUsageRequest}, {}};

static void InitDefaultsCpuUsageResponse() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::systemmonitor::_CpuUsageResponse_default_instance_;
    new (ptr) ::systemmonitor::CpuUsageResponse();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::systemmonitor::CpuUsageResponse::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_CpuUsageResponse =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsCpuUsageResponse}, {}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_CpuUsageRequest.base);
  ::google::protobuf::internal::InitSCC(&scc_info_CpuUsageResponse.base);
}

::google::protobuf::Metadata file_level_metadata[2];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::systemmonitor::CpuUsageRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::systemmonitor::CpuUsageResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::systemmonitor::CpuUsageResponse, usage_percent_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::systemmonitor::CpuUsageRequest)},
  { 5, -1, sizeof(::systemmonitor::CpuUsageResponse)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::systemmonitor::_CpuUsageRequest_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::systemmonitor::_CpuUsageResponse_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "System_Monitor.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 2);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\024System_Monitor.proto\022\rsystemmonitor\"\021\n"
      "\017CpuUsageRequest\")\n\020CpuUsageResponse\022\025\n\r"
      "usage_percent\030\001 \001(\0022a\n\rSystemMonitor\022P\n\013"
      "GetCpuUsage\022\036.systemmonitor.CpuUsageRequ"
      "est\032\037.systemmonitor.CpuUsageResponse\"\000b\006"
      "proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 206);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "System_Monitor.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_System_5fMonitor_2eproto
namespace systemmonitor {

// ===================================================================

void CpuUsageRequest::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

CpuUsageRequest::CpuUsageRequest()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_System_5fMonitor_2eproto::scc_info_CpuUsageRequest.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:systemmonitor.CpuUsageRequest)
}
CpuUsageRequest::CpuUsageRequest(const CpuUsageRequest& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:systemmonitor.CpuUsageRequest)
}

void CpuUsageRequest::SharedCtor() {
}

CpuUsageRequest::~CpuUsageRequest() {
  // @@protoc_insertion_point(destructor:systemmonitor.CpuUsageRequest)
  SharedDtor();
}

void CpuUsageRequest::SharedDtor() {
}

void CpuUsageRequest::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* CpuUsageRequest::descriptor() {
  ::protobuf_System_5fMonitor_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_System_5fMonitor_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const CpuUsageRequest& CpuUsageRequest::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_System_5fMonitor_2eproto::scc_info_CpuUsageRequest.base);
  return *internal_default_instance();
}


void CpuUsageRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:systemmonitor.CpuUsageRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _internal_metadata_.Clear();
}

bool CpuUsageRequest::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:systemmonitor.CpuUsageRequest)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
  handle_unusual:
    if (tag == 0) {
      goto success;
    }
    DO_(::google::protobuf::internal::WireFormat::SkipField(
          input, tag, _internal_metadata_.mutable_unknown_fields()));
  }
success:
  // @@protoc_insertion_point(parse_success:systemmonitor.CpuUsageRequest)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:systemmonitor.CpuUsageRequest)
  return false;
#undef DO_
}

void CpuUsageRequest::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:systemmonitor.CpuUsageRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:systemmonitor.CpuUsageRequest)
}

::google::protobuf::uint8* CpuUsageRequest::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:systemmonitor.CpuUsageRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:systemmonitor.CpuUsageRequest)
  return target;
}

size_t CpuUsageRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:systemmonitor.CpuUsageRequest)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void CpuUsageRequest::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:systemmonitor.CpuUsageRequest)
  GOOGLE_DCHECK_NE(&from, this);
  const CpuUsageRequest* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const CpuUsageRequest>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:systemmonitor.CpuUsageRequest)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:systemmonitor.CpuUsageRequest)
    MergeFrom(*source);
  }
}

void CpuUsageRequest::MergeFrom(const CpuUsageRequest& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:systemmonitor.CpuUsageRequest)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

}

void CpuUsageRequest::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:systemmonitor.CpuUsageRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CpuUsageRequest::CopyFrom(const CpuUsageRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:systemmonitor.CpuUsageRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CpuUsageRequest::IsInitialized() const {
  return true;
}

void CpuUsageRequest::Swap(CpuUsageRequest* other) {
  if (other == this) return;
  InternalSwap(other);
}
void CpuUsageRequest::InternalSwap(CpuUsageRequest* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata CpuUsageRequest::GetMetadata() const {
  protobuf_System_5fMonitor_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_System_5fMonitor_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void CpuUsageResponse::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int CpuUsageResponse::kUsagePercentFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

CpuUsageResponse::CpuUsageResponse()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_System_5fMonitor_2eproto::scc_info_CpuUsageResponse.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:systemmonitor.CpuUsageResponse)
}
CpuUsageResponse::CpuUsageResponse(const CpuUsageResponse& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  usage_percent_ = from.usage_percent_;
  // @@protoc_insertion_point(copy_constructor:systemmonitor.CpuUsageResponse)
}

void CpuUsageResponse::SharedCtor() {
  usage_percent_ = 0;
}

CpuUsageResponse::~CpuUsageResponse() {
  // @@protoc_insertion_point(destructor:systemmonitor.CpuUsageResponse)
  SharedDtor();
}

void CpuUsageResponse::SharedDtor() {
}

void CpuUsageResponse::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* CpuUsageResponse::descriptor() {
  ::protobuf_System_5fMonitor_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_System_5fMonitor_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const CpuUsageResponse& CpuUsageResponse::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_System_5fMonitor_2eproto::scc_info_CpuUsageResponse.base);
  return *internal_default_instance();
}


void CpuUsageResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:systemmonitor.CpuUsageResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  usage_percent_ = 0;
  _internal_metadata_.Clear();
}

bool CpuUsageResponse::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:systemmonitor.CpuUsageResponse)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // float usage_percent = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(13u /* 13 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &usage_percent_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:systemmonitor.CpuUsageResponse)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:systemmonitor.CpuUsageResponse)
  return false;
#undef DO_
}

void CpuUsageResponse::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:systemmonitor.CpuUsageResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // float usage_percent = 1;
  if (this->usage_percent() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(1, this->usage_percent(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:systemmonitor.CpuUsageResponse)
}

::google::protobuf::uint8* CpuUsageResponse::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:systemmonitor.CpuUsageResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // float usage_percent = 1;
  if (this->usage_percent() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(1, this->usage_percent(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:systemmonitor.CpuUsageResponse)
  return target;
}

size_t CpuUsageResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:systemmonitor.CpuUsageResponse)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // float usage_percent = 1;
  if (this->usage_percent() != 0) {
    total_size += 1 + 4;
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void CpuUsageResponse::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:systemmonitor.CpuUsageResponse)
  GOOGLE_DCHECK_NE(&from, this);
  const CpuUsageResponse* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const CpuUsageResponse>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:systemmonitor.CpuUsageResponse)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:systemmonitor.CpuUsageResponse)
    MergeFrom(*source);
  }
}

void CpuUsageResponse::MergeFrom(const CpuUsageResponse& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:systemmonitor.CpuUsageResponse)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.usage_percent() != 0) {
    set_usage_percent(from.usage_percent());
  }
}

void CpuUsageResponse::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:systemmonitor.CpuUsageResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CpuUsageResponse::CopyFrom(const CpuUsageResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:systemmonitor.CpuUsageResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CpuUsageResponse::IsInitialized() const {
  return true;
}

void CpuUsageResponse::Swap(CpuUsageResponse* other) {
  if (other == this) return;
  InternalSwap(other);
}
void CpuUsageResponse::InternalSwap(CpuUsageResponse* other) {
  using std::swap;
  swap(usage_percent_, other->usage_percent_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata CpuUsageResponse::GetMetadata() const {
  protobuf_System_5fMonitor_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_System_5fMonitor_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace systemmonitor
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::systemmonitor::CpuUsageRequest* Arena::CreateMaybeMessage< ::systemmonitor::CpuUsageRequest >(Arena* arena) {
  return Arena::CreateInternal< ::systemmonitor::CpuUsageRequest >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::systemmonitor::CpuUsageResponse* Arena::CreateMaybeMessage< ::systemmonitor::CpuUsageResponse >(Arena* arena) {
  return Arena::CreateInternal< ::systemmonitor::CpuUsageResponse >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
