// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: system_monitor.proto

#include "system_monitor.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include "google/protobuf/generated_message_tctable_impl.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace systemmonitor {

inline constexpr CpuUsageResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : usage_percent_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR CpuUsageResponse::CpuUsageResponse(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct CpuUsageResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CpuUsageResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~CpuUsageResponseDefaultTypeInternal() {}
  union {
    CpuUsageResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CpuUsageResponseDefaultTypeInternal _CpuUsageResponse_default_instance_;
      template <typename>
PROTOBUF_CONSTEXPR CpuUsageRequest::CpuUsageRequest(::_pbi::ConstantInitialized) {}
struct CpuUsageRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CpuUsageRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~CpuUsageRequestDefaultTypeInternal() {}
  union {
    CpuUsageRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CpuUsageRequestDefaultTypeInternal _CpuUsageRequest_default_instance_;
}  // namespace systemmonitor
static ::_pb::Metadata file_level_metadata_system_5fmonitor_2eproto[2];
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_system_5fmonitor_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_system_5fmonitor_2eproto = nullptr;
const ::uint32_t TableStruct_system_5fmonitor_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(
    protodesc_cold) = {
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::systemmonitor::CpuUsageRequest, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::systemmonitor::CpuUsageResponse, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::systemmonitor::CpuUsageResponse, _impl_.usage_percent_),
};

static const ::_pbi::MigrationSchema
    schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::systemmonitor::CpuUsageRequest)},
        {8, -1, -1, sizeof(::systemmonitor::CpuUsageResponse)},
};

static const ::_pb::Message* const file_default_instances[] = {
    &::systemmonitor::_CpuUsageRequest_default_instance_._instance,
    &::systemmonitor::_CpuUsageResponse_default_instance_._instance,
};
const char descriptor_table_protodef_system_5fmonitor_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n\024system_monitor.proto\022\rsystemmonitor\"\021\n"
    "\017CpuUsageRequest\")\n\020CpuUsageResponse\022\025\n\r"
    "usage_percent\030\001 \001(\0022a\n\rSystemMonitor\022P\n\013"
    "GetCpuUsage\022\036.systemmonitor.CpuUsageRequ"
    "est\032\037.systemmonitor.CpuUsageResponse\"\000b\006"
    "proto3"
};
static ::absl::once_flag descriptor_table_system_5fmonitor_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_system_5fmonitor_2eproto = {
    false,
    false,
    206,
    descriptor_table_protodef_system_5fmonitor_2eproto,
    "system_monitor.proto",
    &descriptor_table_system_5fmonitor_2eproto_once,
    nullptr,
    0,
    2,
    schemas,
    file_default_instances,
    TableStruct_system_5fmonitor_2eproto::offsets,
    file_level_metadata_system_5fmonitor_2eproto,
    file_level_enum_descriptors_system_5fmonitor_2eproto,
    file_level_service_descriptors_system_5fmonitor_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_system_5fmonitor_2eproto_getter() {
  return &descriptor_table_system_5fmonitor_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_system_5fmonitor_2eproto(&descriptor_table_system_5fmonitor_2eproto);
namespace systemmonitor {
// ===================================================================

class CpuUsageRequest::_Internal {
 public:
};

CpuUsageRequest::CpuUsageRequest(::google::protobuf::Arena* arena)
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
  // @@protoc_insertion_point(arena_constructor:systemmonitor.CpuUsageRequest)
}
CpuUsageRequest::CpuUsageRequest(
    ::google::protobuf::Arena* arena,
    const CpuUsageRequest& from)
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
  CpuUsageRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);

  // @@protoc_insertion_point(copy_constructor:systemmonitor.CpuUsageRequest)
}









::google::protobuf::Metadata CpuUsageRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_system_5fmonitor_2eproto_getter, &descriptor_table_system_5fmonitor_2eproto_once,
      file_level_metadata_system_5fmonitor_2eproto[0]);
}
// ===================================================================

class CpuUsageResponse::_Internal {
 public:
};

CpuUsageResponse::CpuUsageResponse(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:systemmonitor.CpuUsageResponse)
}
CpuUsageResponse::CpuUsageResponse(
    ::google::protobuf::Arena* arena, const CpuUsageResponse& from)
    : CpuUsageResponse(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE CpuUsageResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void CpuUsageResponse::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.usage_percent_ = {};
}
CpuUsageResponse::~CpuUsageResponse() {
  // @@protoc_insertion_point(destructor:systemmonitor.CpuUsageResponse)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void CpuUsageResponse::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void CpuUsageResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:systemmonitor.CpuUsageResponse)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.usage_percent_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* CpuUsageResponse::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2> CpuUsageResponse::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_CpuUsageResponse_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // float usage_percent = 1;
    {::_pbi::TcParser::FastF32S1,
     {13, 63, 0, PROTOBUF_FIELD_OFFSET(CpuUsageResponse, _impl_.usage_percent_)}},
  }}, {{
    65535, 65535
  }}, {{
    // float usage_percent = 1;
    {PROTOBUF_FIELD_OFFSET(CpuUsageResponse, _impl_.usage_percent_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kFloat)},
  }},
  // no aux_entries
  {{
  }},
};

::uint8_t* CpuUsageResponse::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:systemmonitor.CpuUsageResponse)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // float usage_percent = 1;
  static_assert(sizeof(::uint32_t) == sizeof(float),
                "Code assumes ::uint32_t and float are the same size.");
  float tmp_usage_percent = this->_internal_usage_percent();
  ::uint32_t raw_usage_percent;
  memcpy(&raw_usage_percent, &tmp_usage_percent, sizeof(tmp_usage_percent));
  if (raw_usage_percent != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(
        1, this->_internal_usage_percent(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:systemmonitor.CpuUsageResponse)
  return target;
}

::size_t CpuUsageResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:systemmonitor.CpuUsageResponse)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // float usage_percent = 1;
  static_assert(sizeof(::uint32_t) == sizeof(float),
                "Code assumes ::uint32_t and float are the same size.");
  float tmp_usage_percent = this->_internal_usage_percent();
  ::uint32_t raw_usage_percent;
  memcpy(&raw_usage_percent, &tmp_usage_percent, sizeof(tmp_usage_percent));
  if (raw_usage_percent != 0) {
    total_size += 5;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData CpuUsageResponse::_class_data_ = {
    CpuUsageResponse::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* CpuUsageResponse::GetClassData() const {
  return &_class_data_;
}

void CpuUsageResponse::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<CpuUsageResponse*>(&to_msg);
  auto& from = static_cast<const CpuUsageResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:systemmonitor.CpuUsageResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  static_assert(sizeof(::uint32_t) == sizeof(float),
                "Code assumes ::uint32_t and float are the same size.");
  float tmp_usage_percent = from._internal_usage_percent();
  ::uint32_t raw_usage_percent;
  memcpy(&raw_usage_percent, &tmp_usage_percent, sizeof(tmp_usage_percent));
  if (raw_usage_percent != 0) {
    _this->_internal_set_usage_percent(from._internal_usage_percent());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void CpuUsageResponse::CopyFrom(const CpuUsageResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:systemmonitor.CpuUsageResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool CpuUsageResponse::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* CpuUsageResponse::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void CpuUsageResponse::InternalSwap(CpuUsageResponse* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
        swap(_impl_.usage_percent_, other->_impl_.usage_percent_);
}

::google::protobuf::Metadata CpuUsageResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_system_5fmonitor_2eproto_getter, &descriptor_table_system_5fmonitor_2eproto_once,
      file_level_metadata_system_5fmonitor_2eproto[1]);
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace systemmonitor
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
