// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: system_monitor.proto

#include "system_monitor.pb.h"
#include "system_monitor.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace systemmonitor {

static const char* SystemMonitor_method_names[] = {
  "/systemmonitor.SystemMonitor/GetCpuUsage",
};

std::unique_ptr< SystemMonitor::Stub> SystemMonitor::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< SystemMonitor::Stub> stub(new SystemMonitor::Stub(channel, options));
  return stub;
}

SystemMonitor::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_GetCpuUsage_(SystemMonitor_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status SystemMonitor::Stub::GetCpuUsage(::grpc::ClientContext* context, const ::systemmonitor::CpuUsageRequest& request, ::systemmonitor::CpuUsageResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::systemmonitor::CpuUsageRequest, ::systemmonitor::CpuUsageResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetCpuUsage_, context, request, response);
}

void SystemMonitor::Stub::async::GetCpuUsage(::grpc::ClientContext* context, const ::systemmonitor::CpuUsageRequest* request, ::systemmonitor::CpuUsageResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::systemmonitor::CpuUsageRequest, ::systemmonitor::CpuUsageResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetCpuUsage_, context, request, response, std::move(f));
}

void SystemMonitor::Stub::async::GetCpuUsage(::grpc::ClientContext* context, const ::systemmonitor::CpuUsageRequest* request, ::systemmonitor::CpuUsageResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetCpuUsage_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::systemmonitor::CpuUsageResponse>* SystemMonitor::Stub::PrepareAsyncGetCpuUsageRaw(::grpc::ClientContext* context, const ::systemmonitor::CpuUsageRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::systemmonitor::CpuUsageResponse, ::systemmonitor::CpuUsageRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetCpuUsage_, context, request);
}

::grpc::ClientAsyncResponseReader< ::systemmonitor::CpuUsageResponse>* SystemMonitor::Stub::AsyncGetCpuUsageRaw(::grpc::ClientContext* context, const ::systemmonitor::CpuUsageRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetCpuUsageRaw(context, request, cq);
  result->StartCall();
  return result;
}

SystemMonitor::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      SystemMonitor_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< SystemMonitor::Service, ::systemmonitor::CpuUsageRequest, ::systemmonitor::CpuUsageResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](SystemMonitor::Service* service,
             ::grpc::ServerContext* ctx,
             const ::systemmonitor::CpuUsageRequest* req,
             ::systemmonitor::CpuUsageResponse* resp) {
               return service->GetCpuUsage(ctx, req, resp);
             }, this)));
}

SystemMonitor::Service::~Service() {
}

::grpc::Status SystemMonitor::Service::GetCpuUsage(::grpc::ServerContext* context, const ::systemmonitor::CpuUsageRequest* request, ::systemmonitor::CpuUsageResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace systemmonitor

